
<h1><?php echo $this->escape($this->title); ?></h1>

<?php if(!empty($this->message)) :?>
<div id="message">
<?php echo "<font color='red'>" . $this->escape($this->message) . "</font>";?>
</div>
<?php endif; ?>

<form action="<?php echo $this->baseUrl ?>/cc1/edit" method="post">
<div>
    <label for="newval">Wert</label>
    <input type="text" name="newval" value=""/>
	<input type="hidden" name="cc1" value="<?php echo $this->entries['cc1'] ?>"  />
	<input type="hidden" name="userdef" value="<?php echo $this->entries['userdef'] ?>"  />
</div>
<br>
<div id="formbutton">
<input type="submit" name="save" value="Speichern" />
<?php if ($this->entries['userdef'] > 0) : ?>
<input type="submit" name="reset" value="Rücksetzen" />
<?php endif ?>
<input type="submit" name="cancel" value="Abbrechen" />
</div>
</form>

