    <?php 
	 $logger = Zend_Registry::get('logger');
	 $logger->debug( 'scrpis/cc1/index.phtml> '. ' print table');
	 
	 $url1 = $this->url(array('controller'=>'cc1','action' => 'index'), 'default', true);
	 print '<h2>Warenkorb [<a href="' . $url1 . '">cc1</a>]</h2>';
	 
	 print '<table border=1>';
	 print '<tr><th>CC1</th><th>Bezeichnung</th><th>VPI</th><th>PVPI</th></tr>';
	 $data = $this->entries['DATA'];
	 foreach ($data as $entry) {
	    $cc1 = $entry['CC1'];
		$bezeichnung = $entry['CC1_BEZEICHNUNG'];
		$vpi = $entry['CC1_VPI'];
		$val = $entry['VAL'];
		$userDef = $entry['USER_DEF'];
		$url = $this->url(array('controller'=>'cc2','action' => 'index', 'cc1' => $cc1), 'default', true);
	    print '<tr>';
		print '<td>' . $this->escape($cc1) . '</td>';
		print  '<td><a href="' . $url .     '">' . $this->escape($bezeichnung) .'</a>' . '</td>'; 
		print '<td align ="right">' . $this->escape($vpi) . '</td>';
		if ($userDef == 1) {
		     print '<td align ="right"><font color="blue"><b>' . $this->escape($val) . '</b></font></td>';
	    } else {
		     print '<td align ="right">' . $this->escape($val) . '</td>';
		}
	    print '</tr>';
	  }
	  print '</table>';
	?>
