    <?php 
	 require_once ( APPLICATION_PATH . '\wk_util\wk_util.php');
	 
	 $url1 = $this->url(array('controller'=>'cc1','action' => 'index'), 'default', true);
	 print '<h2>Warenkorb [<a href="' . $url1 . '">cc1</a>]</h2>';
	 $corr = $this->entries['CORR'];
	 print '<h3>Korrelation: ' . $this->escape(wk_number_format($corr)) . '</h3>';
	 print '<table border=1>';
	 print '<tr><th>CC1</th><th>Bezeichnung</th><th>VPI</th><th>PVPI</th></tr>';
	 $data = $this->entries['DATA'];
	 foreach ($data as $entry) {
	    $cc1 = $entry['CC1'];
		$bezeichnung = $entry['CC1_BEZEICHNUNG'];
		$vpi = $entry['CC1_VPI'];
		$val = $entry['VAL'];
		$userDef = $entry['USER_DEF'];
		$url = $this->url(array('controller'=>'cc2','action' => 'index', 'cc1' => $cc1), 'default', true);
	    print '<tr>';
		print '<td>' . $this->escape($cc1) . '</td>';
		print  '<td><a href="' . $url .     '">' . $this->escape($bezeichnung) .'</a>' . '</td>'; 
		print '<td align ="right">' . $this->escape(wk_number_format($vpi)) . '</td>';
		$url = $this->url(array('controller'=>'cc1','action' => 'edit', 'cc1' => $cc1, 'userdef' => $userDef), 'default', true);
		if ($userDef == 1) {
		     print  '<td align ="right"><a href="' . $url . '"><font color="blue"><b>' . $this->escape(wk_number_format($val)) .'</b></font></a></td>'; 
	    } elseif ($userDef == 2) {
		     print  '<td align ="right"><a href="' . $url . '"><font color="red"><b>' . $this->escape(wk_number_format($val)) .'</b></font></a></td>'; 
		} else {
			 print  '<td align ="right"><a href="' . $url . '"><font color="black">' . $this->escape(wk_number_format($val)) .'</font></a></td>'; 
		}
	    print '</tr>';
	  }
	  print '</table>';
	  print '<br>';
	  //$corr = $this->entries['CORR'];
	// print '<h3>Korrelation: ' . $this->escape(wk_number_format($corr)) . '</h3>';
	?>
