
<h2><font color="blue">Hauptgruppen: </font></h2>

    <?php 
	 $logger = Zend_Registry::get('logger');
	 $logger->debug( __FILE__ . ' print table');
	  print "<table border=1>";
	  print "<tr><th>CC1</th><th>Bezeichnung</th><th>VPI</th><th>HVPI</th></tr>";
	  foreach ($this->entries as $entry) {
	    print "<tr>";
		print "<td>" . $this->escape($entry->cc1) . "</td><td>" . $this->escape($entry->cc1_bezeichnung) . "</td>";
		print "<td>" . $this->escape($entry->cc1_vpi) . "</td><td>" . $this->escape($entry->cc1_hvpi) . "</td>";
	     print "</tr>";
	  }
	  print "</table>";
	?>
