
<h2><font color="blue">Untergruppen CC3: </font></h2>

    <?php 
	 $logger = Zend_Registry::get('logger');
	 $logger->debug( 'scrpis/cc3/index.phtml> '. ' print table');
	  print '<table border=1>';
	  print '<tr><th>CC1x</th><th>CC2xx</th><th>CC3</th><th>Bezeichnung</th><th>VPI</th></tr>';
	  foreach ($this->entries as $entry) {
	  	$cc1 = $entry['CC1'];
	    $cc2 = $entry['CC2'];
		$cc3 = $entry['CC3'];
		$bezeichnung = $entry['CC3_BEZEICHNUNG'];
		$vpi = $entry['CC3_VPI'];
		$hvpi = $entry['CC3_HVPI'];
		$url = $this->url(array('controller'=>'cc3','action' => 'index', 'cc1' => $cc1, 'cc2' => $cc2), 'default', true);
	    print '<tr>';
	    print '<td>' . $this->escape($cc1) . '</td>';
		print '<td>' . $this->escape($cc2) . '</td>';
		print '<td>' . $this->escape($cc3) . '</td>';
		print  '<td><a href="' . $url .     '">' . $this->escape($bezeichnung) .'</a>' . '</td>'; 
		print '<td>' . $this->escape($vpi) . '</td>';
		//print '<td>' . $this->escape($hvpi) . '</td>';
	    print '</tr>';
	  }
	  print '</table>';
	?>
