  <?php 	
  		$wp_id 	= $this->rs[0]['WP_ID'];
	  	$user_id = $this->rs[0]['USER_ID'];
	    $wkid = $this->rs[0]['WK_ID'];
			$ist_vpi = $this->rs[0]['IST_VPI'];
			
			$flag = "I";
			if (empty($wp_id)){
				echo "<h2>==>to insert";
			}else{
				echo "to update";
				$flag = "U";
			}
		?>

		  
<form action="<?php echo $this->baseUrl ?>/auth/modify" method="post">
<div>
    <table>
    	<tr>
    		<td>wp_id:<td>
    		<td><input type="text" name="wp_id" value="<?php echo $wp_id ?>"/><td>
    	</tr>	
    	
    	    	<tr>
    		<td>user_id:<td>
    		<td><input type="text" name="user_id" value="<?php echo $user_id ?>"/><td>
    	</tr>	
    	
    	    	<tr>
    		<td>IST_VPI:<td>
    		<td><input type="text" name="newvpi" value="<?php echo $ist_vpi ?>"/><td>
    	</tr>	
    	
    	    	<tr>
    		<td>cc1_id:<td>
    		<td><input type="text" name="cc1_id" value="<?php echo $wkid ?>"/><td>
    	</tr>	
    </table>
    <input type="text" name="flag" value="<?php echo $flag ?>"/>
</div>

<div id="formbutton">
<input type="submit" name="modify" value="Speichern" />
</div>
</form>