<?php 
     require_once ( APPLICATION_PATH . '\wk_util\wk_util.php');
	 $link = $this->entries['LINK'];
	 
	 $url1 = $this->url(array('controller'=>'cc1','action' => 'index'), 'default', true);
	 $url2 = $this->url(array('controller'=>'cc2','action' => 'index', 'cc1' => $link['CC1']), 'default', true);
	 print '<div class="divcenter">';
	 print '<h2>Persönlicher Warenkorb </h2>';
	 print '<h3>[ <a href="' . $url1 . '">' . WK_TXT_CC1 . '</a> / ';
	 print '<a href="' . $url2 . '">' . WK_TXT_CC2 . '</a> ]</h3>';
	 
	 $corr = $this->entries['CORR'];
	 print '<h3>Korrelation: ' . $this->escape(wk_number_format($corr,2)) . '%</h3>';
	 
	 $data = $this->entries['DATA'];
	 
	  print '<table border="1" align="center">';
	  print '<tr><th>CC1</th><th>CC2</th><th>Bezeichnung</th><th>VPI</th><th>PVPI</th></tr>';
	  foreach ($data as $entry) {
	    $cc1 = $entry['CC1'];
		$cc2 = $entry['CC2'];
		$bezeichnung = $entry['CC2_BEZEICHNUNG'];
		$vpi = $entry['CC2_VPI'];
		$db_val = $entry['VAL'];
		$val = wk_number_format($db_val,2);
		$db_val = wk_number_format($db_val);
		$userDef = $entry['USER_DEF'];
		$url = $this->url(array('controller'=>'cc3','action' => 'index', 'cc1' => $cc1, 'cc2' => $cc2), 'default', true);
		print '<tr>';
		print '<td>' . $this->escape($cc1) . '</td>';
		print '<td>' . $this->escape($cc2) . '</td>';
		print  '<td class="tdleft"><a href="' . $url .     '">' . $this->escape($bezeichnung) .'</a>' . '</td>'; 
		print '<td align ="right">' . $this->escape(wk_number_format($vpi)) . '</td>';
		$url = $this->url(array('controller'=>'cc2','action' => 'edit', 'cc1' => $cc1, 'cc2' => $cc2,
		                  'userdef' => $userDef, 'val' => $db_val), 'default', true);
		if ($userDef === WK_VAL_USER) {
		     print  '<td align ="right"><a href="' . $url . '"><font color="blue"><b>' . $this->escape($val) .'</b></font></a></td>'; 
		} elseif($userDef === WK_VAL_DEFAULT) {
		     print  '<td align ="right"><a href="' . $url . '"><font color="black">' . $this->escape($val) .'</font></a></td>'; 
	    } elseif ($userDef === WK_VAL_NOT_EDITABLE) {
		     print  '<td align ="right"><b>' . $this->escape($val) . '</b></td>'; 
		}
	    print '</tr>';
	  }
	  print '</table>';
	  print '</div>';
?>
