
<h1>Persönlicher Warenkorb</h1>

<h2><?php echo $this->escape($this->title); ?></h2>

<?php if(!empty($this->message)) :?>
<div id="message">
<?php echo "<font color='red'>" . $this->escape($this->message) . "</font>" ;?>
</div>
<?php endif; ?>

<form name="createform" action="<?php echo $this->baseUrl ?>/auth/create" method="post">
<table border=1>
 <tr>
    <td><label for="username">Name</label></td>
    <td><input type="text" name="username" value=""/></td>
</tr>
<tr>
    <td><label for="password">Passwort</label></td>
    <td><input type="password" name="password" value=""/></td>
</tr>
</table>
<br>
<div id="formbutton">
<input type="submit" name="create" value="Registrieren" />
</div>
</form>

