<div class="divcenter">
<P ><FONT size=5 ><B>Verbraucherpreisindex, Warenkorb</B></FONT></P>
<P align="left">Der Lebenshaltungskostenindex oder Verbraucherpreisindex(VPI) misst die Veränderung des Geldwertes anhand der Preise der für die Lebenshaltung wichtigen Güter und Dienstleistungen (Lebenshaltungskosten). Ausgangspunkt ist der so genannte Warenkorb, der eine große Anzahl (z.Zt. 780) von Gütern und Dienstleistungen des typischen Verbrauchs enthält.

Ausgehend vom einem Basisjahr, dessen Preise gleich 100 % gesetzt werden, ermittelt man die prozentuale Veränderung der Preise (und damit auch die Veränderung der Kaufkraft) im Vergleich mit dem Basisjahr für einzelne Warengruppen (z. B. Nahrungs- und Genussmittel, Kleidung, Miete) und für die Lebenshaltung insgesamt. Preisveränderungen werden auch im Vergleich zum Vorjahr ermittelt.
<p>
Unter einem sogenannten repräsentativen Warenkorb versteht man auf dem Gebiet der Wirtschaftswissenschaften die Zusammenstellung einer möglichst repräsentativen Anzahl verschiedener Güter zur Ermittlung des Preisindex und der Inflation. Die Preisentwicklung der enthaltenen Güter wird dabei über eine bestimmte Zeit (z. B. vier Jahre) mit konstanter Gewichtung der einzelnen Positionen ermittelt.
<p>
Üblicherweise versteht man unter dem Warenkorb den, der für die Berechnung des Verbraucherpreisindex (VPI) verwendet wird. Dieser berücksichtigt die anteiligen Ausgaben der privaten Haushalte für die entsprechenden Güterkategorien.
<p>
In Österreich wird der Warenkorb für den Verbraucherpreisindex von der Statistik Austria erstellt. Von 1966 bis 1996 wurde der Warenkorb alle zehn Jahre aktualisiert (VPI 66 bis VPI 96). Aufgrund von Vorgaben von Eurostat findet die Anpassung des Warenkorbes nun alle fünf Jahre statt. Aktuell ist der VPI 2005, die nächste Aktualisierung wird im Jahr 2010 stattfinden, die neue Indexreihe ab Januar 2011 veröffentlicht. Der Warenkorb umfasst unter anderem Getreideprodukte, Fleischwaren, Fisch, Milch, Käse, Eier, Fette, Öle, Obst und Gemüse einschließlich Kartoffeln.
<p>
Der harmonisierte Verbraucherpreisindex (HVPI) ist ein in der Europäischen Union erhobener Verbraucherpreisindex, dem ein EU-weit einheitlicher Warenkorb zugrunde liegt. Der HVPI ist die Kennzahl, mit der in der Europäischen Wirtschafts- und Währungsunion (EWWU) die Preisniveauentwicklung gemessen wird. 

<P ><FONT size=5 ><B>Warenkorb</B></FONT></P>
<p>Das aktuelle Programm ermöglicht die Ermittlung der Relevanz der Inflation für den persönlichen Warenkorb. Dazu werden aus 646 Gütern und Dienstleistungen des täglichen Bedarfs, jene ausgewählt, welche sich im persönlichen Warenkorb befinden, sowie deren prozentueller Anteil am Gesamtbudget.
<P><FONT size=3> 1.)Warenbereiche (Abteilungen)(CC1)&nbsp;<BR>&nbsp;&nbsp;&nbsp;&nbsp; (Anzahl 12)</FONT></P>

<TABLE border="1" align="center" >
  <TBODY>
  <TR>
    <TD class="tdleft"><FONT size=3>1</FONT></TD>
    <TD class="tdleft">NAHRUNGSMITTEL UND ALKOHOLFREIE GETRÄNKE</TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>2</FONT></TD>
    <TD class="tdleft"><FONT size=3>ALKOHOLISCHE GETRÄNKE UND TABAK</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>3</FONT></TD>
    <TD class="tdleft"><FONT size=3>BEKLEIDUNG UND SCHUHE</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>4</FONT></TD>
    <TD class="tdleft"><FONT size=3>WOHNUNG, WASSER, ENERGIE</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>5</FONT></TD>
    <TD class="tdleft"><FONT size=3>HAUSRAT UND LAUFENDE INSTANDHALTUNG DES HAUSES</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>6</FONT></TD>
    <TD class="tdleft"><FONT size=3>GESUNDHEITSPFLEGE</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>7</FONT></TD>
    <TD class="tdleft"><FONT size=3>VERKEHR</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>8</FONT></TD>
    <TD class="tdleft"><FONT size=3>NACHRICHTENÜBERMITTLUNG</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>9</FONT></TD>
    <TD class="tdleft"><FONT size=3>FREIZEIT UND KULTUR</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>10</FONT></TD>
    <TD class="tdleft"><FONT size=3>ERZIEHUNG UND UNTERRICHT</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>11</FONT></TD>
    <TD class="tdleft"><FONT size=3>RESTAURANTS UND HOTELS</FONT></TD></TR>
  <TR>
    <TD class="tdleft"><FONT size=3>12</FONT></TD>
    <TD class="tdleft"><FONT size=3>VERSCHIEDENE WAREN UND DIENSTLEISTUNGEN</FONT></TD></TR>
</TBODY></TABLE><BR>

<P><FONT size=3>2.) Jeder dieser Bereiche besitzt untergeordnete 
Gliederungen, genannt Warenarten (CC2).&nbsp;<BR>&nbsp;&nbsp;&nbsp;&nbsp; 
(Anzahl 45)</FONT></P>


<h3>Der Warenbereich&nbsp;&nbsp; 4 
      WOHNUNG, WASSER, ENERGIE ist untergliedert in folgende Warenarten:</h3>

      <TABLE border="1" align="center">
        <TBODY>
        <TR>
          <TD class="tdleft"><FONT size=3>1</FONT></TD>
          <TD class="tdleft"><FONT size=3>Gezahlte Wohnungsmieten</FONT></TD></TR>
        <TR>
          <TD class="tdleft"><FONT size=3>2</FONT></TD>
          <TD class="tdleft"><FONT size=3>Ausgaben für Eigentumswohnungen</FONT></TD></TR>
        <TR>
          <TD class="tdleft"><FONT size=3>3</FONT></TD>
          <TD class="tdleft"><FONT size=3>Instandhaltung und Reparatur der 
            Wohnung</FONT></TD></TR>
        <TR>
          <TD class="tdleft"><FONT size=3>4</FONT></TD>
          <TD class="tdleft"><FONT size=3>Wasserversorgung und sonstige Dienstleistungen im Zusammenhang mit der Wohnung</FONT></TD></TR>
        <TR>
          <TD class="tdleft"><FONT size=3>5</FONT></TD>
          <TD class="tdleft"><FONT size=3>Elektrizität. Gas und andere Brennstoffe</FONT></TD></TR>
</TBODY></TABLE><BR></TD></TR>

<P><FONT size=3>3.) Jeder dieser Warenart besitzt untergeordnete Gliederungen,genannt Warengruppen 
      (CC3).&nbsp;<BR>&nbsp;&nbsp;&nbsp;&nbsp; (Anzahl 106)</FONT> &nbsp;<BR><BR></P><A 
      name=0.1_table04></A>
	  <h3>Die Warenart 5 Elektrizität. Gas und andere 
      Brennstoffe untergliedert sich in folgende Warengruppen:</h3>
      <TABLE border="1" align="center">
        <TBODY>
        <TR>
          <TD class="tdleft"><FONT size=3>1</FONT></TD>
          <TD class="tdleft"><FONT size=3>Elektrizität</FONT></TD></TR>
        <TR>
          <TD class="tdleft"><FONT size=3 >2</FONT></TD>
          <TD class="tdleft"><FONT size=3>Gas</FONT></TD></TR>
        <TR>
          <TD class="tdleft"><FONT size=3>3</FONT></TD>
          <TD class="tdleft"><FONT size=3>Flüssige Brennstoffe</FONT></TD></TR>
        <TR>
          <TD class="tdleft"><FONT size=3>4</FONT></TD>
          <TD class="tdleft"><FONT size=3>Feste Brennstoffe</FONT></TD></TR>
        <TR>
          <TD class="tdleft"><FONT size=3>5</FONT></TD>
          <TD class="tdleft"><FONT size=3>Wärmeenergie</FONT></TD></TR></TBODY></TABLE><BR>

<P><FONT size=3>4.) Jede Warengruppe enthält schließlich die 
      einzelnen Waren&nbsp;<BR>&nbsp;&nbsp;&nbsp;&nbsp;  (Anzahl 646)</FONT></P>
    <h3>Im Falle der Warengruppe 5 Wärmeenergie, 
    besteht diese aus folgenden Waren:</h3>  
      <TABLE border="1" align="center">
        <TBODY>
        
              <TR>
                <TD class="tdleft"><FONT size=3>570</FONT></TD>
                <TD class="tdleft"><FONT size=3>Fernheizung, Grundgebühr</FONT></TD>
              </TR>
              <TR>
                <TD class="tdleft"><FONT size=3>571</FONT></TD>
                <TD class="tdleft"><FONT size=3>Fernheizung, Arbeitspreis</FONT></TD>
                </TR></TBODY></TABLE><BR></TD></TR>
				
<p>
Der Warenkorb kann auf jeder der vier Ebene, den prsönliche Ausgaben angepasst werden.   
Die Eingabe des persönlichen VPI Wertes (PVPI) erfolgt durch die
Angabe des prozentuelle Anteil einer einzelnen Ware, einer Warengruppe, einer Warenart oder eines Warenbereiches
am Gesamtwarenkorb.</p><p>
 Um doppelte Eingaben auf verschiedenen Ebenen zu vermeiden, 
 zB. Den Prozentsatz einer Warengruppe, welche schon in einer eingegebenen Warenart enthalten ist, 
 verhindert das Programm, dass Eingaben auf einer unteren Gliederungsebene gemacht werden können, 
 sobald auf einer übergeordneten Ebene bereits eine Eingabe erfolgt ist. 
</p>
<p>
Beispiel: Hat man für eine bestimmte Gruppe (zB. Wärmeenergie) bereits einen Anteil am Warenkorb eingegeben,
so kann für die einzelnen Waren dieser Gruppe (Fernheizung Grundgebühr und Fernheizung Arbeitspreis) keine Werte mehr eingeben.

</p>
<p>
Die Summe der prozentuellen Anteile der einzelnen Waren/Warenkategorien darf 100% nicht übersteigen,
der Anteil darf aber weniger als 100% sein. 
Die Differenz zu 100% wird in der Zeile Sonstiges (Ebene Warenbereiche) angezeigt.
</p>


</div>