
<P align=center><FONT size=5 ><B>Persönlicher Warenkorb </B></FONT></P>
<P><FONT size=3>Mit diesem Programm kann man ermitteln, zu welchem 
Prozentsatz der eigene Haushalt von der Inflation betroffen ist. Dazu werden aus 
646 Gütern und Dienstleistungen des täglichen Bedarfs, jene ausgewählt, welche 
sich im eigenen Warenkorb befinden, sowie deren prozentueller Anteil.
</FONT></P>
<P><FONT size=3> 1.)Warenbereiche 
(CC1)&nbsp;<BR>&nbsp;&nbsp;&nbsp;&nbsp; (Anzahl 12)</FONT></P>
<DIV align=left>
<TABLE border=2 cellSpacing=0 width=605>
  <TBODY>
  <TR vAlign=top>
    <TD height=15><FONT size=3>1</FONT></TD>
    <TD><FONT size=3>NAHRUNGSMITTEL UND ALKOHOLFREIE GETRÄNKE</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>2</FONT></TD>
    <TD><FONT size=3>ALKOHOLISCHE GETRÄNKE UND TABAK</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>3</FONT></TD>
    <TD><FONT size=3>BEKLEIDUNG UND SCHUHE</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>4</FONT></TD>
    <TD><FONT size=3>WOHNUNG, WASSER, ENERGIE</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>5</FONT></TD>
    <TD><FONT size=3>HAUSRAT UND LAUFENDE INSTANDHALTUNG DES HAUSES</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>6</FONT></TD>
    <TD><FONT size=3>GESUNDHEITSPFLEGE</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>7</FONT></TD>
    <TD><FONT size=3>VERKEHR</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>8</FONT></TD>
    <TD><FONT size=3>NACHRICHTENÜBERMITTLUNG</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>9</FONT></TD>
    <TD><FONT size=3>FREIZEIT UND KULTUR</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>10</FONT></TD>
    <TD><FONT size=3>ERZIEHUNG UND UNTERRICHT</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>11</FONT></TD>
    <TD><FONT size=3>RESTAURANTS UND HOTELS</FONT></TD></TR>
  <TR vAlign=top>
    <TD height=15><FONT size=3>12</FONT></TD>
    <TD><FONT size=3>VERSCHIEDENE WAREN UND DIENSTLEISTUNGEN</FONT></TD></TR>
</TBODY></TABLE></DIV>&nbsp;<BR>

<P><FONT size=3>2.) Jeder dieser Bereiche besitzt untergeordnete 
Gliederungen, genannt Warenarten (CC2).&nbsp;<BR>&nbsp;&nbsp;&nbsp;&nbsp; 
(Anzahl 45)</FONT></P>

<DIV align=left>
<FONT size=3>Der Warenbereich&nbsp;&nbsp; 4 
      WOHNUNG, WASSER, ENERGIE ist untergliedert in folgende Warenarten:</FONT>&nbsp;<BR><BR>

      <TABLE border=2 cellSpacing=0 width=601>
        <TBODY>
        <TR vAlign=top>
          <TD><FONT size=3>1</FONT></TD>
          <TD><FONT size=3>Gezahlte Wohnungsmieten</FONT></TD></TR>
        <TR vAlign=top>
          <TD><FONT size=3>2</FONT></TD>
          <TD><FONT size=3>Ausgaben für Eigentumswohnungen</FONT></TD></TR>
        <TR vAlign=top>
          <TD><FONT size=3>3</FONT></TD>
          <TD><FONT size=3>Instandhaltung und Reparatur der 
            Wohnung</FONT></TD></TR>
        <TR vAlign=top>
          <TD><FONT size=3>4</FONT></TD>
          <TD><FONT size=3>Wasserversorgung und sonstige Dienstleistungen im Zusammenhang mit der Wohnung</FONT></TD></TR>
        <TR vAlign=top>
          <TD><FONT size=3>5</FONT></TD>
          <TD><FONT size=3>Elektrizität. Gas und andere Brennstoffe</FONT></TD></TR>
</TBODY></TABLE></DIV>&nbsp;<BR></TD></TR>

<P><FONT size=3>3.) Jeder dieser Warenart besitzt untergeordnete Gliederungen,genannt Warengruppen 
      (CC3).&nbsp;<BR>&nbsp;&nbsp;&nbsp;&nbsp; (Anzahl 106)</FONT> &nbsp;<BR><BR></P><A 
      name=0.1_table04></A>
	  <P><FONT size=3>Die Warenart 5 Elektrizität. Gas und andere 
      Brennstoffe untergliedert sich in folgende Warengruppen :</FONT></P>
	  <DIV align=left>
      <TABLE border=2 cellSpacing=0 width=601>
        <TBODY>
        <TR vAlign=top>
          <TD><FONT size=3>1</FONT></TD>
          <TD><FONT size=3>Elektrizität</FONT></TD></TR>
        <TR vAlign=top>
          <TD><FONT size=3 >2</FONT></TD>
          <TD><FONT size=3>Gas</FONT></TD></TR>
        <TR vAlign=top>
          <TD><FONT size=3>3</FONT></TD>
          <TD><FONT size=3>Flüssige Brennstoffe</FONT></TD></TR>
        <TR vAlign=top>
          <TD><FONT size=3>4</FONT></TD>
          <TD><FONT size=3>Feste Brennstoffe</FONT></TD></TR>
        <TR vAlign=top>
          <TD><FONT size=3>5</FONT></TD>
          <TD><FONT size=3>Wärmeenergie</FONT></TD></TR></TBODY></TABLE></DIV>&nbsp;<BR>

<P><FONT size=3>4.) Jede Warengruppe enthält schließlich die 
      einzelnen Waren&nbsp;<BR>&nbsp;&nbsp;&nbsp;&nbsp;  (Anzahl 646)</FONT></P>
      <P><FONT size=3>Im Falle der Warengruppe 5 Wärmeenergie, 
      besteht diese aus folgenden Waren :</FONT></P>	  
<DIV align=left>
      <TABLE border=2 cellSpacing=0  width=601>
        <TBODY>
        
              <TR vAlign=top>
                <TD><FONT size=3>570</FONT></TD>
                <TD><FONT size=3>Fernheizung, Grundgebühr</FONT></TD>
              </TR>
              <TR vAlign=top>
                <TD><FONT size=3>571</FONT></TD>
                <TD><FONT size=3>Fernheizung, Arbeitspreis</FONT></TD>
                </TR></TBODY></TABLE></DIV>&nbsp;<BR></TD></TR>
				
<P><FONT size=3>
         Es 
            kann nun der eigene Warenkorb eingegeben werden und zwar auf jeder 
            Ebene der 4 Untergliederungsarten.&nbsp; Für jede Ware oder Gruppe kann der 
            prozentuelle Anteil am Gesamtwarenkorb eingegeben werden.
			
			
            Um widersprüchliche  Eingaben auf verschiedenen Ebenen zu vermeiden, 
			zB. Den Prozentsatz 
            einer Warenart, welche schon in einer eingegebenen Warengruppe 
            enthalten ist, verhindert das Programm, daß Eingaben auf einer 
            niedrigeren Gliederungsebene gemacht werden können.</FONT> 
			
