<div class="divcenter">
<h1>Persönlicher Warenkorb</h1>
Das aktuelle Programm ermöglicht die Ermittlung der Relevanz der Inflation für den persönlichen Warenkorb.<br><br>


<?php
$url0 = $this->url(array('controller'=>'auth','action' => 'help'), 'default', true);
print '<a href="' . $url0 . '">Mehr Informationen zum Persönlichen Warenkorb</a>';
?>

<h3><?php echo $this->escape($this->title); ?></h3>


<?php if(!empty($this->message)) :?>
<div id="message">
<?php echo "<font color='red'>" . $this->escape($this->message) . "</font>";?>
</div>
<?php endif; ?>

<form name="loginform" action="<?php echo $this->baseUrl ?>/auth/login" method="post">
<table border="1" align="center">
    <tr>
    <td class="tdleft"><label for="username">Name</label></td>
    <td><input type="text" name="username" value=""/></td>
     </tr><tr>
    <td class="tdleft"><label for="password">Passwort</label></td>
    <td><input type="password" name="password" value=""/></td>
</table>

<br>
<div id="formbutton">
<input type="submit" name="login" value="Anmelden" />
</div>
</form>
</div>

