
<h1>Persönlicher Warenkorb</h1>

<p>Mit diesem Programm kann man ermitteln, zu welchem Prozentsatz<br> der eigene Haushalt von der Inflation betroffen ist.<br>
<p>

<?php
$url0 = $this->url(array('controller'=>'auth','action' => 'help'), 'default', true);
print 'Mehr Informationen zum <a href="' . $url0 . '"><b>Persönlichen Warenkorb<b></a>';
?>

<h2><?php echo $this->escape($this->title); ?></h2>


<?php if(!empty($this->message)) :?>
<div id="message">
<?php echo "<font color='red'>" . $this->escape($this->message) . "</font>";?>
</div>
<?php endif; ?>

<form name="loginform" action="<?php echo $this->baseUrl ?>/auth/login" method="post">
<table border=1>
    <tr>
    <td><label for="username">Name</label></td>
    <td><input type="text" name="username" value=""/></td>
     </tr><tr>
    <td><label for="password">Passwort</label></td>
    <td><input type="password" name="password" value=""/></td>
    </tr>
</table>
<br>
<div id="formbutton">
<input type="submit" name="login" value="Anmelden" />
</div>
</form>

