
<h2><?php echo $this->escape($this->title); ?></h2>

<?php if(!empty($this->message)) :?>
<div id="message">
<?php echo "<font color='red'>" . $this->escape($this->message) . "</font>";?>
</div>
<?php endif; ?>

<form name="editform" action="<?php echo $this->baseUrl ?>/waren/edit" method="post">
<div>
 <table border=1>
 <tr>    
    <td><label for="newval">Neuer PVPI Wert</label></td>
    <td><input type="text" name="newval" value="<?php echo $this->entries['val'] ?>"/></td>
</tr>
</table>
	<input type="hidden" name="cc1" value="<?php echo $this->entries['cc1'] ?>"  />
	<input type="hidden" name="cc2" value="<?php echo $this->entries['cc2'] ?>"  />
	<input type="hidden" name="cc3" value="<?php echo $this->entries['cc3'] ?>"  />
	<input type="hidden" name="id" value="<?php echo $this->entries['id'] ?>"  />
	<input type="hidden" name="warencode" value="<?php echo $this->entries['warencode'] ?>"  />
	<input type="hidden" name="userdef" value="<?php echo $this->entries['userdef'] ?>"  />
</div>
<br>
<div id="formbutton">
<input type="submit" name="save" value="Speichern" />
<?php if ($this->entries['userdef'] > 0) : ?>
<input type="submit" name="reset" value="Rücksetzen" />
<?php endif ?>
<input type="submit" name="cancel" value="Abbrechen" />
</div>
</form>

