<?php 
// application/layouts/scripts/layout.phtml
echo $this->doctype();
$auth = Zend_Auth::getInstance();
$isLoggedIn  = $auth->hasIdentity();
$userName = $auth->getIdentity()->USER_NAME;
?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html " /> 
  <title>Zend Framework Warenkorb Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head> 
<?php if (is_array($this->entries) and array_key_exists('ONLOAD',$this->entries)) : ?>
  <body onload="<?php print $this->entries['ONLOAD'] ?> ">
<?php else : ?>
<body>
<?php endif; ?>
<div id="header" style="background-color: #EEEEEE; height: 40px;">
    <?php  if ($isLoggedIn) :  ?>
	<div id="header-logo" style="float: left">
        <b><font color='green'> <?php echo "$userName ist angemeldet" ?> </font></b>
    </div>
	<?php else : ?>
	<div id="header-logo" style="float: left">
        <b><font color='red'> Kein Benutzer angemeldet</font></b>
    </div>
	<?php endif ?>
	
    <div id="header-navigation" style="float: right">
	    <?php 
	      if ($isLoggedIn) :  ?>
            <a href="<?php echo $this->url(
            array('controller'=>'auth','action' => 'logout'), 
            'default', 
            true) ?>"><font color='green'>Abmelden</font></a>
		<?php else : ?>
		<a href="<?php echo $this->url(
            array('controller'=>'auth','action' => 'create'), 
            'default', 
            true) ?>"><font color='red'>Neuen Benutzer registrieren</font></a>
		<?php endif ?>
    </div>
</div>

<?php echo $this->layout()->content ?>

</body>
</html>
