<!-- application/views/scripts/warenkorb/index.phtml -->


	<table border="0">
		<tr>
			<td>Name: </td>
			<td><input type="text" value="abc"></td>
		</tr>	
			<tr>
			<td>Password: </td>
			<td><input type="password" value="123456"></td>
		</tr>	
		
				<tr>
			<td colspan="2" align="right"><a href="<?php echo $this->url(
            array('controller'=>'warenkorb',
            			'action'=>'index'), 
            'default', 
            true) ?>><b>Sign in</b></a></td>
		</tr>	
	</table>	
</dl>
